/* Plugin generated by AMXX-Studio */

#include <amxmodx>
#include <amxmisc>
#include <hamsandwich>
#include <fakemeta>
#include <td>

#define PLUGIN "TD Head Shot damage multplier"
#define VERSION "1.0"
#define AUTHOR "GT TEAM"

#define monster_headshot		pev_euser2

new Float:DamageCvar
public plugin_init() {
	register_plugin(PLUGIN, VERSION, AUTHOR);
	RegisterHam(Ham_TraceAttack, "info_target", "TraceAttack");
	
	new pcvar = create_cvar("td_headshot_multiplier", "1.5", _, _, true, 1.0, true, 50.0)
	bind_pcvar_float(pcvar, DamageCvar)
}

public TraceAttack(iEnt, idattacker, Float:damage, Float:direction[3], tracehandle, damagebits)
{
	new hitbox = get_tr2(tracehandle, TR_iHitgroup);

	if(pev(iEnt, pev_iuser1) == _:ROUND_NONE)
		return HAM_IGNORED;
	
	if(hitbox == HIT_HEAD){
		set_pev(iEnt, monster_headshot, 1)
		SetHamParamFloat(3, damage*DamageCvar);
		return HAM_HANDLED;
	} else set_pev(iEnt, monster_headshot, 0)
	
	return HAM_IGNORED;
}
